/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylx_ability_jni_JNIUtils */

#ifndef _Included_com_ylx_ability_jni_JNIUtils
#define _Included_com_ylx_ability_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylx_ability_jni_JNIUtils
 * Method:    getName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring Java_com_ylx_ability_jni_JNIUtils_getName
        (JNIEnv *, jclass, jstring);

JNIEXPORT jint Java_com_ylx_ability_jni_JNIUtils_init
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
